[versions]
fastutil = "8.2.1"
kotlinStdlibJdk8 = "1.8.20-RC2"
slf4jApi = "2.0.9"
log4jSlf4jImpl = "2.20.0"
kotlinLogging = "5.1.0"
jacksonDataformatYaml = "2.14.2"
jacksonDataformatToml = "2.13.0"
jacksonDatabind = "2.13.0"
mssqlJdbc = "6.4.0.jre7"
json = "20220320"
jbcrypt = "0.4"
gson = "_"
cacheor = "1.0.4"
cacherl = "_"
kotlinxSerializationCore = "_"
junit = "4.+"
kotlinTestJunit = "_"
kotlin = "1.8.10"
openrs2 = "0.1.0-SNAPSHOT"
nettyAll = "4.0.34.Final"
slf4j = "2.0.0-alpha0"
csv = "0.7.3"
logback = "1.4.11"
displee = "7.1.0"
sparkCore = "2.3"
progress = "0.9.2"

[libraries]
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlinStdlibJdk8" }

displee = { group = "com.displee", name = "rs-cache-library", version.ref = "displee" }
progress-bar = { group = "me.tongfei", name = "progressbar", version.ref = "progress" }

# Leaving for now, will be removed in the future
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jApi" }
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4jSlf4jImpl" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging", version.ref = "kotlinLogging" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jacksonDataformatYaml" }
jackson-dataformat-toml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-toml", version.ref = "jacksonDataformatToml" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jacksonDatabind" }
jackson-module-kotlin = {group ="com.fasterxml.jackson.module" , name = "jackson-module-kotlin", version = "2.13.0" }
mssql-jdbc = { group = "com.microsoft.sqlserver", name = "mssql-jdbc", version.ref = "mssqlJdbc" }
json = { group = "org.json", name = "json", version.ref = "json" }
reflection = {group = "org.reflections", name = "reflections", version = "_"}
jbcrypt = { group = "org.mindrot", name = "jbcrypt", version.ref = "jbcrypt" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
cache-rl = { group = "net.runelite", name = "cache", version.ref = "cacherl" }
cache-or = { group = "dev.openrune", name= "filestore", version.ref = "cacheor"}
kotlin-scripting = {group = "org.jetbrains.kotlin", name = "kotlin-scripting-common", version = "_"}
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin"}
kotlinx-coroutines = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "_"}
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
commons = { group = "commons-io", name = "commons-io", version = "_"}
implementation = { group = "io.github.classgraph", name  = "classgraph", version = "_"}
bouncycastle = { group = "org.bouncycastle", name =  "bcprov-jdk15on",version = "_"}
classgraph = { group = "io.github.classgraph", name = "classgraph", version = "4.8.157"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlinTestJunit"}
kotlin-csv = { group = "com.github.doyaaaaaken", name = "kotlin-csv", version.ref = "csv"}

openrs2-cache = { module = "org.openrs2:openrs2-cache", version.ref = "openrs2"}
openrs2-buffer = { module = "org.openrs2:openrs2-buffer", version.ref = "openrs2"}
openrs2-crypto = { module = "org.openrs2:openrs2-crypto", version.ref = "openrs2"}
openrs2-compress = { module = "org.openrs2:openrs2-compress", version.ref = "openrs2"}

netty-all = { group = "io.netty", name = "netty-all", version.ref = "nettyAll" }

logback-classic = { group ="ch.qos.logback", name = "logback-classic", version.ref = "logback"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version =  "0.9.18"}
shadow = { id ="com.github.johnrengelman.shadow", version = "8.1.1"}